### ISSUE TITLE
可以同时支持多个repository

### ISSUE THREAD

**Issue by Vence** [litten/hexo-theme-yilia#229]
请问在_config.yml中deploy中可以设置多个repository吗？

如果我想把静态博客部署到多个git地址上，如coding和github上，请问该如何做？

**Comment by daikanshan** [comment]
这个和主题无关，在根目录的_config.yml中设置即可
```yml
# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo:
    github: git@github.com:username/username.github.io.git,master
    coding: git@git.coding.net:username/username.git,master
```

> 最后记得在coding static page的设置中修改为master分支
