### ISSUE TITLE
主页头像正常显示，打开文章后头像不显示

### ISSUE THREAD

**Issue by yf-web** [litten/hexo-theme-yilia#331]
操作完全按照教程来的，主页上各个内容正常显示，点击打开某一文章后，个人头像不显示，求指点，谢谢！主题配置文件内容如下：

```
menu:
 
subnav:
  github: "yf.github.com"
  #douban: "#"
  mail: "yf@163.com"

root: 

excerpt_link: more
fancybox: true
mathjax: false

animate: true

open_in_new: false

google_analytics: ''
favicon: /favicon.png

avatar: images/logo/9548.jpg

share_jia: true
share_addthis: false

duoshuo: false
```
