### ISSUE TITLE
超长行内代码不会自动换行

### ISSUE THREAD

**Issue by douxingxiang** [litten/hexo-theme-yilia#37]
截图，
![2015-03-14 21 01 24](https://cloud.githubusercontent.com/assets/1589027/6651754/6bbb8f82-ca8e-11e4-8f8e-cbe00100e89d.png)
对应markdown文件片段：
<pre>
位置`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk`
</pre>
可以修改`article.styl`
``` css
p code,li code{
    padding: 1px 3px;
    margin: 0 3px;
    background: #f1f1f1;
    border: 1px solid #ccc;
    font-family: font-mono;
    word-wrap: break-word;//自动换行
  }
```
