### ISSUE TITLE
电脑和手机菜单展开后背景能否自定义修改

### ISSUE THREAD

**Issue by fingdo** [litten/hexo-theme-yilia#377]

**Comment by litten** [comment]
可以了，请更新一下
在```_config.yml```里使用以下配置：

```
# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'
```

元旦快乐
