### ISSUE TITLE
所有文章 友好链接 关于博客 在移动设备上不好看

### ISSUE THREAD

**Issue by iHTCboy** [litten/hexo-theme-yilia#378]
以前的黑色风格比较高大上点，现在淡绿茶色 不好看，我应用怎么改？或者增加几个主题色？

**Comment by litten** [comment]
可以了，请更新一下
在```_config.yml```里使用以下配置：

```
# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'
```

元旦快乐
