### ISSUE TITLE
如何修改侧边栏

### ISSUE THREAD

**Issue by Tomoya-Hoo** [litten/hexo-theme-yilia#380]
想修改侧边栏的宽度与背景，可是修改了left.scss里面的一些参数(.left-col{ background ;width} .overlay{background-color )不起作用

**Comment by litten** [comment]
需要编译，请看文档[《Yilia源码目录结构及构建须知》](https://github.com/litten/hexo-theme-yilia/wiki/Yilia%E6%BA%90%E7%A0%81%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E5%8F%8A%E6%9E%84%E5%BB%BA%E9%A1%BB%E7%9F%A5)

如果仅仅是修改背景，用配置即可：

```
# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'
```

看文档*3 …
