### ISSUE TITLE
menu / subnav / smart_menu 等属性更改不生效

### ISSUE THREAD

**Issue by geekinglcq** [litten/hexo-theme-yilia#398]
如题，在`_config.yml`中更改某些属性后`hexo clean; hexo g; hexo s`，但是查看发现更改不生效。
比如设置：
```
menu:
  主页: /
  test: /tags/test/
....
smart_menu:
  innerArchive: '所有文章'
  friends: 'test'
  aboutme: 'try me'
```   
但是还是显示：
![qq 20170115213802](https://cloud.githubusercontent.com/assets/9047780/21962924/f312c63c-db6a-11e6-86f0-4ef7b6b42e4f.png)

同时头像也未正确显示，控制台报`http://localhost:4000/null/ Failed to load resource: the server responded with a status of 404 (Not Found)`，尝试了之前issues的各类方法都不管用。  
奇怪的是`_config.yml`中title等属性更改倒是没有问题。
另外，如果有帮助的话，观察到，即使在`_config.yml`更改了这些属性，然后`hexo g`的时候并不会重新生成`index.html`,(更改`title`,`subtitle`等属性倒是会生成新的`index.html`)

求大神支招Orz
