### ISSUE TITLE
求教怎么修改侧边栏背景图片

### ISSUE THREAD

**Issue by Johnnyluke** [litten/hexo-theme-yilia#450]
2017.3.23的版本

**Comment by fxlddd** [comment]
YILIAZ主题中修改头像背景图片在/themes/yilia/layout/_partial/left-col.ejs文件中的第二行中，例如我目前改动的:

<div class="overlay" style="background: url('http://fanxinlong.com/assets/img/background.jpg') no-repeat center bottom;background-size: cover;"></div>

**Comment by fxlddd** [comment]
YILIAZ主题中修改头像背景图片在/themes/yilia/layout/_partial/left-col.ejs文件中的第二行中，例如目前改动的:
```
<div class="overlay" style="background: url('http://fanxinlong.com/assets/img/background.jpg') no-repeat center bottom;background-size: cover;"></div>
```

**Comment by litten** [comment]
看README
```
# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'
```
