### ISSUE TITLE
关于yilia主题支持Markdown渲染的问题

### ISSUE THREAD

**Issue by CharlesLiuyx** [litten/hexo-theme-yilia#519]
在yilia主题下不支持 or hexo不支持？但是看到hexo的说明里能支持github flavored markdown语法啊
- [ ] 前面是标志完成或者未完成的语法 
![在主题内显示出来的情况](https://cloud.githubusercontent.com/assets/21956621/26416323/554950aa-406a-11e7-907e-e21f10ac616a.png )

**Comment by NoahDragon** [comment]
是否是用的hexo-renderer-marked？0.3.0版本应该已经支持了https://github.com/hexojs/hexo-renderer-marked/pull/32

**Comment by CharlesLiuyx** [comment]
应该是的

 ~/Github/lyxblog  npm ls --depth 0
hexo-site@0.0.0 /Users/charlesliuyx/Github/lyxblog
├── ejs@2.5.6 extraneous
├── hexo@3.3.5
├── hexo-deployer-git@0.3.0
├── hexo-deployer-rsync@0.1.3
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-json-content@3.0.1
├── hexo-generator-tag@0.2.0
├── hexo-inject@1.0.0
├── UNMET DEPENDENCY hexo-math@^3.0.2
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-marked@0.3.0
├── hexo-renderer-stylus@0.3.3
├── hexo-server@0.2.0
├── sass@0.5.0 extraneous
└── webpack@2.5.1 extraneous

npm ERR! missing: hexo-math@^3.0.2, required by hexo-site@0.0.0
npm ERR! extraneous: ejs@2.5.6 /Users/charlesliuyx/Github/lyxblog/node_modules/ejs
npm ERR! extraneous: sass@0.5.0 /Users/charlesliuyx/Github/lyxblog/node_modules/sass
npm ERR! extraneous: webpack@2.5.1 /Users/charlesliuyx/Github/lyxblog/node_modules/webpack

**Comment by NoahDragon** [comment]
在hexo目录下的_config.yml文件中，是否有marked设置？

**Comment by CharlesLiuyx** [comment]
没有怎么改过Hexo目录下的_config.yml

```yml
# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
highlight:                                                                                                                                                                                                   
  enable: true                                                                                                                                                                                               
  auto_detect: true                                                                                                                                                                                          
  line_number: true                                                                                                                                                                                          
  tab_replace: ''

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 1
category: 1
tag: 1
```
