### ISSUE TITLE
jsonContent缺失提示中的添加配置多缩进了1倍。

### ISSUE THREAD

**Issue by maosgithub** [litten/hexo-theme-yilia#576]
```yml
jsonContent:
    meta: false
    pages: false
    posts:
      title: true
      date: true
      path: true
      text: false
      raw: false
      content: false
      slug: false
      updated: false
      comments: false
      link: false
      permalink: false
      excerpt: false
      categories: false
      tags: true
```
