### ISSUE TITLE
“more”标签不生效，展开全文可以

### ISSUE THREAD

**Issue by xingguanxiaohai** [litten/hexo-theme-yilia#577]
你好我不知道我这为什么more不生效，但是展开全文是可以的，还有一个问题，就是 “所有文章” 我是在一个目录下的 但点开就是根目录。。。导致路径不对出不来

**Comment by xingguanxiaohai** [comment]
在文章中加？ 是么~我这个解决了

**Comment by xingguanxiaohai** [comment]
permalink: <路径>/:year/:month/:day/:title/   这样就可以了

**Comment by mrpsweet** [comment]
在文章中想要截断的地方加上

**Comment by cxytomo** [comment]
我会用成功的进行了截断显示，但是我不想页面上同时出现>>more和展开全文，请问>>more怎么去掉？用样式隐藏？

**Comment by xingguanxiaohai** [comment]
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'

**Comment by FanWalker** [comment]
如果不想同时出现more 和展开全文，我是把main.266c1c.css样式给改了，隐藏掉了more

**Comment by cxytomo** [comment]
@FanWalker 我也是这么做的。。

**Comment by Echo009** [comment]
隐藏more，显示展开全文，在css文件中添加样式
``` css
p.article-more-link > a.article-more-a {
  display: inline-block;!important;
}
a.article-more-a {
  display: none;;
}
```
