### ISSUE TITLE
hexo: 3.1.1版本 里貌似不支持代码高亮了..

### ISSUE THREAD

**Issue by SeriousMa** [litten/hexo-theme-yilia#68]
而且line-number成1了..
![image](https://cloud.githubusercontent.com/assets/464213/7957433/f0a25dc8-0a19-11e5-8bc2-7a067196121c.png)

**Comment by litten** [comment]
好，周末看一下

**Comment by SeriousMa** [comment]
多谢

**Comment by SeriousMa** [comment]
![image](https://cloud.githubusercontent.com/assets/464213/7999343/3de77cf4-0b7c-11e5-9bde-532fd6755bc0.png)
相关环境

**Comment by alfredtofu** [comment]
@SeriousMa @litten 3.1.1开始，不支持代码自动检测，需要把自动检测属性设为true，站点配置：
```
highlight:                                                                                                                                                                                                   
  enable: true                                                                                                                                                                                               
  auto_detect: true                                                                                                                                                                                          
  line_number: true                                                                                                                                                                                          
  tab_replace: ''
```
