### ISSUE TITLE
关于iPad端浏览时 滑动卡顿的问题解决方案

### ISSUE THREAD

**Issue by Ericwww** [litten/hexo-theme-yilia#703]
在CSS文件中，`#container`和`.mid-col`中添加`-webkit-overflow-scrolling:touch;`即可

```CSS
#container{position:relative;min-height:100%;-webkit-overflow-scrolling:touch}

.mid-col{position:absolute;right:0;min-height:100%;background:#eaeaea;left:300px;width:auto;-webkit-overflow-scrolling:touch}

```
