### ISSUE TITLE
点击所有文章，只显示文章标签，没有文章名字列表？

### ISSUE THREAD

**Issue by andyxzq** [litten/hexo-theme-yilia#707]
<img width="365" alt="2018-02-11 6 05 44" src="https://user-images.githubusercontent.com/10462598/36072194-65695956-0f56-11e8-91a9-2cc7748a87b2.png">
如上图::)

**Comment by zer946** [comment]
我也是！按照[这个](http://blog.csdn.net/qq_32337109/article/details/78756041)上的链接试了一下，但还是不行，希望大神解答

**Comment by Qu000** [comment]
我一样是这里有问题，求解答

**Comment by Qu000** [comment]
好吧，解决了，当实在解决不了一个小问题的时候，我选择了最原始的方法，从头来一次，删掉我的node和博客站点，从新部署的

**Comment by Dev-Jabin** [comment]
你好，我能看见文章，但是看不见文章的标题。该怎么解决？

**Comment by yansheng836** [comment]
我遇到了同样的问题，然后对比博主github博客备份，在hexo根目录下的_config.yml文件末尾添加了下面的代码，可以解决该问题。https://github.com/litten/BlogBackup/blob/master/_config.yml#L115-L132
```
#标签不能正常显示的问题
jsonContent:
  meta: false
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: false
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: false
    excerpt: false
    categories: false
    tags: true
```
