### ISSUE TITLE
markdownn中的代码段浏览器看起来有略微重影

### ISSUE THREAD

**Issue by geeeez** [litten/hexo-theme-yilia#837]
发现自己写的文章 中 比如php代码段 生成html后 在博客上看 会略有点朦胧重影，这个样式是主题控制样式还是在哪儿修改css文件啊？现在不知道在哪儿改这个文章的字体和代码段的样式。图片贴下面
![image](https://user-images.githubusercontent.com/29922543/63925337-7d646e00-ca7c-11e9-93ee-a776b82cc6f8.png)

**Comment by colorfulsweet** [comment]
应该是text-shadow导致的
代码在 article.scss的238行
```scss
  pre {
    font-size: 1 / 0.9em;
    line-height: 1.5;
    margin-top: 10px;
    padding: 5px 15px;
    overflow-x: auto;
    color: #657b83;
    font-size: 10px;
    border: 1px solid #ccc;
    text-shadow: 0 1px #444;
    font-family: Menlo,Monaco,"Andale Mono","lucida console","Courier New",monospace;
    code{
      font-size: 14px;
    }
  }
```
