### ISSUE TITLE
希望加入对toc目录的支持

### ISSUE THREAD

**Issue by 52fhy** [litten/hexo-theme-yilia#87]
主题很喜欢！希望加入对toc目录的支持！辛苦啦~

**Comment by misty000** [comment]
加toc很简单，在article.ejs里改一下就好
```html
    <div class="article-entry" itemprop="articleBody">
      <% if (post.excerpt && index){ %>
        <%- post.excerpt %>
      <% } else { %>
        <% if (!index){ %>
        <div id="toc" class="article-toc">
          <%- toc(post.content) %>
          <hr/>
        </div>
        <% } %>
        <%- post.content %>
      <% } %>
    </div>
```
然后根据自己喜好加点样式
```css
#toc{
  .toc {
    padding: 0;
    li {
      list-style-type none;
    }
  }
  ol {
    margin-left 0;
  }
}
```
